#!/usr/bin/env python3
"""Relabel a chromosome-scope FASTA/GFF by the HY4A similarity map without flipping."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import shutil
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from geneloss_repro.chromosome_harmonization import (  # noqa: E402
    HarmonizationError,
    build_actions,
    read_fasta,
    transform_genome,
    transform_gff,
    validate_cds_protein_closure,
    validate_sequence_closure,
    write_fasta,
)


class RelabelError(RuntimeError):
    pass


LABEL_COLUMNS = (
    "query_chromosome",
    "final_chromosome",
    "coordinate_reference",
    "assignment_method",
    "assigned_score",
    "reciprocal_coverage",
    "orientation_to_hy4a",
    "hy4p_and_jcvi_agree",
    "strict_homology_gates_pass",
    "confidence_flag",
)


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def binding(path: Path) -> dict[str, object]:
    source = path.resolve()
    if not source.is_file() or source.stat().st_size <= 0:
        raise RelabelError(f"missing or empty input: {source}")
    return {"basename": source.name, "bytes": source.stat().st_size, "sha256": sha256(source)}


def read_label_map(path: Path) -> tuple[dict[str, str], dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if tuple(reader.fieldnames or ()) != LABEL_COLUMNS:
            raise RelabelError("similarity label-map columns differ from exact schema")
        rows = list(reader)
    if len(rows) != 29:
        raise RelabelError("similarity label map must contain exactly 29 rows")
    source = [row["query_chromosome"] for row in rows]
    final = [row["final_chromosome"] for row in rows]
    if len(set(source)) != 29 or set(final) != {f"Chr{index:02d}" for index in range(1, 30)}:
        raise RelabelError("similarity label map is not a complete Chr01-Chr29 bijection")
    if any(
        row["coordinate_reference"] != "act_chinensis_hongyang_v4_hy4a"
        or row["assignment_method"] != "global_one_to_one_maximum_nucleotide_similarity"
        for row in rows
    ):
        raise RelabelError("label map was not generated by the requested HY4A similarity policy")
    return dict(zip(source, final, strict=True)), {
        row["query_chromosome"]: row["confidence_flag"] for row in rows
    }


def write_checksums(root: Path) -> None:
    path = root / "checksums.tsv"
    with path.open("w", encoding="utf-8", newline="") as handle:
        handle.write("file\tbytes\tsha256\n")
        for item in sorted(root.iterdir()):
            if item.is_file() and item.name != path.name:
                record = binding(item)
                handle.write(f"{item.name}\t{record['bytes']}\t{record['sha256']}\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--unit", required=True)
    parser.add_argument("--label-map", required=True, type=Path)
    parser.add_argument("--genome", required=True, type=Path)
    parser.add_argument("--gff", required=True, type=Path)
    parser.add_argument("--cds", required=True, type=Path)
    parser.add_argument("--protein", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    args = parser.parse_args()
    staging: Path | None = None
    try:
        for path in (args.label_map, args.genome, args.gff, args.cds, args.protein):
            binding(path)
        output = args.output_dir.resolve()
        if output.exists():
            raise RelabelError(f"refusing to overwrite output: {output}")
        final_by_source, confidence = read_label_map(args.label_map)
        source_genome = read_fasta(args.genome)
        if set(source_genome) != set(final_by_source):
            raise RelabelError("source genome IDs differ from similarity label map")
        actions = build_actions(
            source_genome,
            final_by_source,
            {source: "+" for source in source_genome},
        )
        transformed = transform_genome(source_genome, actions)
        expected_cds = read_fasta(args.cds)
        expected_proteins = read_fasta(args.protein)
        output.parent.mkdir(parents=True, exist_ok=True)
        staging = Path(tempfile.mkdtemp(prefix=f".{output.name}.staging.", dir=output.parent))
        genome_output = staging / f"{args.unit}.genome.fa.gz"
        gff_output = staging / f"{args.unit}.primary.gff3"
        cds_output = staging / f"{args.unit}.cds.fa"
        protein_output = staging / f"{args.unit}.protein.faa"
        write_fasta(genome_output, transformed)
        gff_audit = transform_gff(args.gff, gff_output, actions)
        validate_sequence_closure(
            source_genome=source_genome,
            transformed_genome=read_fasta(genome_output),
            actions=actions,
        )
        closure = validate_cds_protein_closure(
            source_genome=source_genome,
            source_gff=args.gff,
            transformed_genome=read_fasta(genome_output),
            transformed_gff=gff_output,
            expected_cds=expected_cds,
            expected_proteins=expected_proteins,
        )
        shutil.copyfile(args.cds, cds_output)
        shutil.copyfile(args.protein, protein_output)
        if sha256(cds_output) != sha256(args.cds) or sha256(protein_output) != sha256(args.protein):
            raise RelabelError("CDS/protein copies are not byte-identical")
        manifest = {
            "schema_version": 1,
            "workflow": "hy4a_similarity_chromosome_relabelling",
            "status": "PASS",
            "unit": args.unit,
            "finished_at_utc": utc_now(),
            "policy": {
                "label_assignment": "global one-to-one maximum HY4A nucleotide similarity",
                "absolute_support_is_naming_blocker": False,
                "direction_action": "preserve publisher direction; relabel only",
            },
            "inputs": {
                "label_map": binding(args.label_map),
                "genome": binding(args.genome),
                "gff": binding(args.gff),
                "cds": binding(args.cds),
                "protein": binding(args.protein),
            },
            "metrics": {
                "chromosomes": len(actions),
                "low_confidence_labels": sum(value == "LOW" for value in confidence.values()),
                "supported_labels": sum(value == "SUPPORTED" for value in confidence.values()),
                "high_confidence_labels": sum(value == "HIGH" for value in confidence.values()),
                "gff": gff_audit,
                "sequence_closure": closure,
            },
        }
        (staging / "run_manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        write_checksums(staging)
        os.rename(staging, output)
        staging = None
        print(f"PASS\t{args.unit}\t29 chromosomes")
        return 0
    except (OSError, UnicodeError, csv.Error, json.JSONDecodeError, RelabelError, HarmonizationError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2
    finally:
        if staging is not None:
            shutil.rmtree(staging, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
